In [ ]:
import pandas as pd
import altair as alt

In [15]:
from google.colab import files
upload = files.upload()

Saving hojatotalcongreso.csv to hojatotalcongreso.csv

In [16]:
df = pd.read_csv("hojatotalcongreso.csv")

In [17]:
df

     Año  Total Congreso  Cámara  Senado
0   1951               1       1       0
1   1953               2       1       1
2   1957               3       3       0
3   1961               5       5       0
4   1965              10      10       0
5   1969               7       7       0
6   1973              16      14       2
7   1990               9       7       2
8   1994              11       9       2
9   1998              15      13       2
10  2002              17      15       2
11  2006              21      19       2
12  2010              22      17       5
13  2014              22      15       7
14  2018              41      31      10
15  2021              10       0      10
16  2022              47      46       1
17  2026              56      41      15

In [18]:
df.columns = df.columns.str.strip()

In [20]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q"
)

alt.Chart(...)

In [21]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q",
    color="Año:N"
)

alt.Chart(...)

In [23]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q",
    color="Año:N"
).properties(
    title="Mujeres en el Congreso en cada elección"
)

alt.Chart(...)

In [26]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q",
    tooltip=["Total Congreso", "Año"],
    color="Año:N"
).properties(
    title="Mujeres en el Congreso en cada elección"
)

alt.Chart(...)

In [29]:
chart = alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q",
    tooltip=["Total Congreso", "Año"],
    color="Año:N"
).properties(
    title="Mujeres en el Congreso en cada elección"
)

chart.save('mujeres_congreso.html')

In [33]:
from google.colab import files
upload = files.upload()

Saving hojatotalcongreso.csv to hojatotalcongreso (2).csv

In [38]:
df = pd.read_csv("hojatotalcongreso.csv")

In [35]:
df

     Año  Total Congreso  Cámara  Senado
0   1951               1       1       0
1   1953               2       1       1
2   1957               3       3       0
3   1961               5       5       0
4   1965              10      10       0
5   1969               7       7       0
6   1973              16      14       2
7   1990               9       7       2
8   1994              11       9       2
9   1998              15      13       2
10  2002              17      15       2
11  2006              21      19       2
12  2010              22      17       5
13  2014              22      15       7
14  2018              41      31      10
15  2021              10       0      10
16  2022              47      46       1
17  2026              56      41      15

In [37]:
df.columns = df.columns.str.strip()

In [39]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Cámara:Q"
)

alt.Chart(...)

In [40]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Cámara:Q",
    color="Año:N"
)

alt.Chart(...)

In [41]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Cámara:Q",
    color="Año:N"
).properties(
    title="Mujeres en la Cámara de Diputados en cada elección"
)

alt.Chart(...)

In [43]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q",
    tooltip=["Cámara", "Año"],
    color="Año:N"
).properties(
    title="Mujeres en la Cámara de Diputados en cada elección"
)

alt.Chart(...)

In [44]:
chart_camara = alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Total Congreso:Q",
    tooltip=["Cámara", "Año"],
    color="Año:N"
).properties(
    title="Mujeres en la Cámara de Diputados en cada elección"
)

chart_camara.save('mujeres_camara.html')

In [46]:
from google.colab import files
upload = files.upload()

Saving hojatotalcongreso.csv to hojatotalcongreso (3).csv

In [47]:
df = pd.read_csv("hojatotalcongreso.csv")

In [48]:
df

     Año  Total Congreso  Cámara  Senado
0   1951               1       1       0
1   1953               2       1       1
2   1957               3       3       0
3   1961               5       5       0
4   1965              10      10       0
5   1969               7       7       0
6   1973              16      14       2
7   1990               9       7       2
8   1994              11       9       2
9   1998              15      13       2
10  2002              17      15       2
11  2006              21      19       2
12  2010              22      17       5
13  2014              22      15       7
14  2018              41      31      10
15  2021              10       0      10
16  2022              47      46       1
17  2026              56      41      15

In [49]:
df.columns = df.columns.str.strip()

In [50]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Senado:Q"
)

alt.Chart(...)

In [51]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Senado:Q",
    color="Año:N"
)

alt.Chart(...)

In [52]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Senado:Q",
    color="Año:N"
).properties(
    title="Mujeres en el Senado en cada elección"
)

alt.Chart(...)

In [53]:
alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Senado:Q",
    tooltip=["Senado", "Año"],
    color="Año:N"
).properties(
    title="Mujeres en el Senado en cada elección"
)

alt.Chart(...)

In [54]:
chart_senado = alt.Chart(df).mark_bar().encode(
    x="Año:N",
    y="Senado:Q",
    tooltip=["Senado", "Año"],
    color="Año:N"
).properties(
    title="Mujeres en el Senado en cada elección"
)

chart_senado.save('mujeres_senado.html')